### ISSUE TITLE
Обработка ошибок на бекенде

### ISSUE THREAD

**Issue by Alov** [Lemain99/teachingAccounting#54]
Добавить обработку ошибок на бекенде, чтобы при возникновении эксепшна был отдан корректный ответ.
Для этого нужно:

- [x] Создать типизированный класс Api
```
{
     "code":415,
     "errorMessage":"some error message",
     "data": T
}
``` 
- [x] Создать класс, антотированный  @RestControllerAdvice.
- [x] Добавить глобальный метод обработки ошибок

Подробнее про обработку ошибок можно почитать здесь: https://www.baeldung.com/exception-handling-for-rest-with-spring

**Comment by Raboofoce** [comment]
Да начнется глиномесня!..
