### ISSUE TITLE
Дополнительная информация в ответе при авторизации

### ISSUE THREAD

**Issue by Alov** [Lemain99/teachingAccounting#66]
В данный момент, при авторизации пользователя в ответ приходит его роль. Если авторизация не прошла возвращается ответ со статусом 401.
Необходимо переделать функционал `AuthenticationSuccessHandler` объявленного в классе `SecurityConfig`.
В ответ должен приходить валидный json, следующего вида:
```
{
    "status": "OK",
    "data": {
         "roles": ["admin"]
     }
}
```

Для этого нужно:
- [ ] Вынести AuthenticationSuccessHandler и AuthenticationFailureHandler в отдельные классы.
- [ ] В созданные классы внедрить ObjectMapper, который будет конвертировать ApiResponse в json.
- [ ] В обработке события успешной авторизации положить в ответ сконвертированный json.

Пример:
```
List<String> roles = ...;
ApiResponse<List<String>> apiResponse = ApiResponse.ok(roles);
String s = objectMapper.write();
response.getOutputStream().println(s)
```

**Comment by Raboofoce** [comment]
https://imgur.com/a/rXkklmG
